import assert from "node:assert/strict";
import test from "node:test";
import { associateManagedContainers, discoverIconCandidates, type DockerSummary } from "../src/server/container-association.ts";
import { resolveUnraidLabelIcon } from "../src/server/container-service.ts";
import type { TemplateRecord } from "../src/server/types.ts";

function template(name: string, fileName: string, icon: string | null = null): TemplateRecord {
  const containerName = fileName.replace(/^my-/, "").replace(/\.xml$/, "").toLowerCase();
  return { name, fileName, filePath: `/templates/${fileName}`, icon, repository: `example/${containerName}:latest` };
}

function deployed(name: string): DockerSummary {
  return {
    Id: `container-${name}`,
    Names: [`/${name}`],
    Image: `example/${name}:latest`,
    State: "running",
    Status: "Up 1 hour"
  };
}

test("associates a deployed container with a template by exact Name", () => {
  const containers = associateManagedContainers([template("plex", "my-plex.xml", "plex.png")], [deployed("plex")]);

  assert.equal(containers.length, 1);
  assert.equal(containers[0].name, "plex");
  assert.equal(containers[0].fileName, "my-plex.xml");
  assert.equal(containers[0].icon, "plex.png");
  assert.equal(containers[0].displayIcon, "plex.png");
  assert.equal(containers[0].displayIconSource, "template");
  assert.equal(containers[0].editable, true);
  assert.equal(containers[0].templateMatch, "name");
});

test("does not claim a template whose Name differs because Unraid will not resolve it", () => {
  const containers = associateManagedContainers([template("Sonarr archive", "my-sonarr.xml", "sonarr.png")], [deployed("sonarr")]);

  assert.equal(containers.length, 1);
  assert.equal(containers[0].name, "sonarr");
  assert.equal(containers[0].fileName, null);
  assert.equal(containers[0].editable, true);
  assert.equal(containers[0].templateMatch, null);
  assert.equal(containers[0].templateState, "will-create");
});

test("requires exact Name matching because Unraid's resolver is case-sensitive", () => {
  const byName = associateManagedContainers([template("PLEX", "my-plex.xml")], [deployed("plex")]);
  const byFile = associateManagedContainers([template("Sonarr archive", "my-SONARR.xml")], [deployed("sonarr")]);

  assert.equal(byName[0].fileName, null);
  assert.equal(byName[0].templateState, "will-create");
  assert.equal(byFile[0].fileName, null);
  assert.equal(byFile[0].templateState, "will-create");
});

test("requires Repository matching after normalizing the latest tag", () => {
  const matching = { ...template("plex", "my-plex.xml"), repository: "example/plex" };
  const stale = { ...template("plex", "my-stale.xml"), repository: "example/plex:old" };
  assert.equal(associateManagedContainers([matching], [deployed("plex")])[0].fileName, "my-plex.xml");
  assert.equal(associateManagedContainers([stale], [deployed("plex")])[0].templateState, "will-create");
});

test("keeps a deployed container without a matching template visible and marks template creation", () => {
  const containers = associateManagedContainers([template("other", "my-other.xml", "other.png")], [deployed("unmatched")]);

  assert.equal(containers.length, 1);
  assert.equal(containers[0].name, "unmatched");
  assert.equal(containers[0].id, "container-unmatched");
  assert.equal(containers[0].fileName, null);
  assert.equal(containers[0].icon, null);
  assert.equal(containers[0].displayIcon, null);
  assert.equal(containers[0].editable, true);
  assert.equal(containers[0].templateMatch, null);
  assert.equal(containers[0].templateState, "will-create");
});

test("does not include stale templates when their Docker container is not deployed", () => {
  const containers = associateManagedContainers(
    [template("active", "my-active.xml"), template("stale", "my-stale.xml")],
    [deployed("active")]
  );

  assert.deepEqual(containers.map((container) => container.name), ["active"]);
});

test("keeps Compose containers editable through Unraid icon metadata without changing Compose", () => {
  const compose = { ...deployed("sonarr"), Labels: { "com.docker.compose.project": "media" } };
  const containers = associateManagedContainers([template("sonarr", "my-sonarr.xml")], [compose]);

  assert.equal(containers[0].editable, true);
  assert.equal(containers[0].fileName, "my-sonarr.xml");
  assert.equal(containers[0].composeManaged, true);
  assert.equal(containers[0].templateState, "linked");
});

test("identifies templates generated by this app", () => {
  const generated = { ...template("worker", "my-worker.xml"), generated: true };
  const containers = associateManagedContainers([generated], [deployed("worker")]);
  assert.equal(containers[0].templateState, "generated");
});

test("discovers explicit Compose/container and local image icon labels without fetching them", () => {
  const candidates = discoverIconCandidates(
    { "com.docker.compose.icon": "https://cdn.example/compose.png", "org.opencontainers.image.url": "https://example.com/project" },
    { "org.opencontainers.image.icon": "https://cdn.example/image.png", "net.unraid.docker.icon": "file:///unsafe.png" }
  );
  assert.deepEqual(candidates, [
    { value: "https://cdn.example/compose.png", source: "container-label", labelKey: "com.docker.compose.icon" },
    { value: "https://cdn.example/image.png", source: "image-label", labelKey: "org.opencontainers.image.icon" }
  ]);
});

test("returns icon candidates only when the current template has no icon", () => {
  const summary = { ...deployed("compose"), Labels: { "com.docker.compose.icon-url": "https://cdn.example/icon.png" } };
  const withoutIcon = associateManagedContainers([], [summary]);
  const withIcon = associateManagedContainers([template("compose", "my-compose.xml", "https://current.example/icon.png")], [summary]);
  assert.equal(withoutIcon[0].iconCandidates.length, 1);
  assert.deepEqual(withIcon[0].iconCandidates, []);
});

test("resolves the exact Unraid icon label without reading arbitrary host paths", () => {
  assert.equal(
    resolveUnraidLabelIcon("http://192.168.1.10:5000/Docker", "/mnt/user/docker/media/icons/app icon.png"),
    "http://192.168.1.10:5000/mnt/user/docker/media/icons/app%20icon.png"
  );
  assert.equal(resolveUnraidLabelIcon("http://unraid/Docker", "https://cdn.example/icon.png"), "https://cdn.example/icon.png");
  assert.equal(resolveUnraidLabelIcon("http://unraid/Docker", "/etc/passwd"), null);
  assert.equal(resolveUnraidLabelIcon("http://unraid/Docker", "/mnt/user/icons/../secret.png"), null);
});
